version: "3"
services:
  web:
    image: kmldqj/leancloud-tester-webapi:latest
    ports:
      - "443:4040"
    depends_on:
      - postgres
    environment:
      - SSL_KEY=/ssl/privkey.pem
      - SSL_CERT=/ssl/fullchain.pem
      - PG_URI=postgres://postgres:insecure@postgres/leancloud_tests
    volumes:
      - ${SSL_DIR}/fullchain.pem:/ssl/fullchain.pem
      - ${SSL_DIR}/privkey.pem:/ssl/privkey.pem
    networks:
      - defaultnet
  storage-tester:
    image: kmldqj/leancloud-tester:latest
    depends_on:
      - postgres
    environment:
      - TEST_NAME=storage
      - PG_URI=postgres://postgres:insecure@postgres/leancloud_tests
      - WAIT_FOR_PORT=postgres:5432
      - APP_ID=${STORAGE_APP_ID}
      - APP_KEY=${STORAGE_APP_KEY}
    networks:
      - defaultnet
  message-tester:
    image: kmldqj/leancloud-tester:latest
    depends_on:
      - postgres
    environment:
      - TEST_NAME=message
      - PG_URI=postgres://postgres:insecure@postgres/leancloud_tests
      - WAIT_FOR_PORT=postgres:5432
      - APP_ID=${STORAGE_APP_ID}
      - APP_KEY=${STORAGE_APP_KEY}
    networks:
      - defaultnet
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=insecure
      - POSTGRES_DB=leancloud_tests
    volumes:
      - /docker-volumes/var/lib/postgresql/data/:/var/lib/postgresql/data/
    networks:
      - defaultnet
networks:
  defaultnet:
